[package]
name = "deep_tch"
version = "0.1.0"
edition = "2021"
license = "LGPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
random = "0.12.2"
rand = "0.8.5"

[dev-dependencies]
proptest = "1.0.0"